---
title: "Never tell me the odds: EotE Dice Simulations"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
---

```{r global, include=FALSE}
library(flexdashboard)
library(shiny)
library(purrr)
library(ggplot2)
# Set up dice sides
sides <- list(
    # Positive dice - boost, ability, proficiency
    "b" = 6,
    "a" = 8,
    "p" = 12,
    # Negative dice - setback, difficulty, challenge
    "s" = 6,
    "d" = 8,
    "c" = 12
)

# Define positive dice ---------------------------------------------------------
successes <- list(
    # Positive dice only - boost, ability, proficiency
    "b" = c(0, 0 , 1, 1, 0, 0),
    "a" = c(0, 1, 1, 2, 0, 0, 1, 0),
    "p" = c(0, 1, 1, 2, 2, 0, 1, 1, 1, 0, 0, 1)
)

advantages <- list(
    # Positive dice only - boost, ability, proficiency
    "b" = c(0, 0, 0, 1, 2, 1),
    "a" = c(0, 0, 0, 0, 1, 1, 1, 2),
    "p" = c(0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 0)
)

triumphs <- list("p" = c(rep(0, 11), 1))

# Define positive dice ---------------------------------------------------------
failures <- list(
    "s" = c(0, 0 , 1, 1, 0, 0),
    "d" = c(0, 1, 2, 0, 0, 0, 0, 1),
    "c" = c(0, 1, 1, 2, 2, 0, 0, 1, 1, 0, 0, 1)
)

threat <- list(
    "s" = c(0, 0 , 0, 0, 1, 1),
    "d" = c(0, 0, 0, 1, 1, 1, 2, 1),
    "c" = c(rep(0, 5), rep(1, 4), 2, 2, 0)
)

despair <- list("c" = c(rep(0, 11), 1))

`%||%` <- rlang::`%||%`
# Functions ---------------------------------------------------------------
roll_die <- function(die) {
    side <- sample(sides[[die]], 1)
    c(
        # Positive results
        suc = successes[[die]][[side]] %||% 0,
        adv = advantages[[die]][[side]] %||% 0,
        tri = triumphs[[die]][[side]] %||% 0,

        # Negative results
        fail = failures[[die]][[side]] %||% 0,
        thre = threat[[die]][[side]] %||% 0,
        desp = despair[[die]][[side]] %||% 0
    )
}

roll_dice <- function(die, times) {
    if ( times == 0 ) {
        c(
            # Positive results
            suc = 0,
            adv = 0,
            tri = 0,
            # Negative results
            fail = 0,
            thre = 0,
            desp = 0
        )
    } else {
        .out <- purrr::map(seq_len(times), ~roll_die(die))
        tapply(unlist(.out), names(unlist(.out)), sum, default = 0L)
    }
}



roll_pool <- function(b = 0, a = 0, p = 0, s = 0, d = 0, c = 0) {
    dice <- list(b, a, p, s, d, c)
    dice <- purrr::set_names(dice, c("b", "a", "p", "s", "d", "c"))
    dice %>%
        purrr::imap(~roll_dice(.y, .x)) %>%
        purrr::map(t) %>%
        purrr::map_dfr(tibble::as_tibble) %>%
        colSums()
}

process_pool <- function(pool_results) {
    pool <- pool_results
    net_success <- pool[["suc"]] - pool[["fail"]]
    net_adv <- pool[["adv"]] - pool[["thre"]]
    c(
        success = net_success,
        advantage = net_adv,
        triumph = pool[["tri"]],
        despair = pool[["desp"]]
        )
}

simulate_pool <- function(times = 100, b = 0, a = 0, p = 0, s = 0, d = 0, c = 0) {
    times <- seq_len(times)
    pools <- purrr::map(times, ~roll_pool(b, c, p, s, d, c))
    processed <- purrr::map(pools, process_pool)
    transf <- purrr::map(processed, t)
    purrr::map_dfr(transf, tibble::as_tibble)
}
```

## {.sidebar}

**Positive dice**

```{r positive-dice}
sliderInput("b", "Boosts (blue):", 0, 6, 0, step = 1)
sliderInput("a", "Ability (green):", 0, 6, 0, step = 1)
sliderInput("p", "Proficiency (yellow):", 0, 6, 0, step = 1)
```

**Negative dice**

```{r negative-dice}
sliderInput("s", "Setback (black):", 0, 6, 0, step = 1)
sliderInput("d", "Difficulty (purple):", 0, 6, 0, step = 1)
sliderInput("c", "Challenge (red):", 0, 6, 0, step = 1)
```

**Simulations**

```{r sims}
sliderInput("sims", "Number of rolls::", 100, 1000, 500, step = 100)
actionButton("simulate", "Simulate!")
```
    

## {data-height=400}

```{r get-results}
results <- eventReactive(input$simulate, {
    input$sims %>% 
        simulate_pool(input$b, input$a, input$p, input$s, input$d, input$c) %>% 
        dplyr::mutate(
            so = dplyr::if_else(success > 0, "Success", "Failure"),
            sa = dplyr::case_when(
                advantage == 0 ~ "",
                advantage > 0 ~ "with advantage",
                TRUE ~ "with threat"
                ),
            to = dplyr::if_else(triumph <= 0, "", "and triumph"),
            do = dplyr::if_else(despair <= 0, "", "and despair"),
            outcome = stringr::str_trim(
                stringr::str_squish(
                    paste(so, sa, to, do)
                )
            )
        ) %>% 
        dplyr::select(success, advantage, triumph, despair, outcome)
})
```


### Success vs. failure

```{r success-dist}
renderPlot({
    req(results())
    ggplot(results(), aes(success, fill = success > 0)) +
        geom_histogram(binwidth = 1) +
        geom_vline(xintercept = 0) +
        labs(
            x = "Failure | Success",
            y = "",
            caption = "Positive values are net succcess, zero and negative values are net failures."
        ) +
        theme(legend.position = "none")
})
```

### Advantage vs. threat

```{r adv-dist}
renderPlot({
    req(results())
    ggplot(results(), aes(advantage, fill = advantage > 0)) +
        geom_histogram(binwidth = 1) +
        geom_vline(xintercept = 0) +
        labs(
            x = "Threat | Advantage",
            y = "",
            caption = "Positive values are net advantage, negative values are net threat."
            ) +
        theme(legend.position = "none")
})
```

##

### Triumph and Despair

```{r}
renderPlot({
    req(results())
    results() %>% 
        dplyr::select(triumph, despair) %>%
        tidyr::gather() %>%
        ggplot(aes(as.factor(value), fill = key)) +
        geom_bar(position = "dodge") +
        scale_fill_manual(values = c("triumph" = "yellow", "despair" = "red")) +
        labs(x = "", y = "") +
        theme(legend.position = "bottom")
})
```

### Net outcome

```{r}
renderPlot({
    req(results())
    outcomes <- results() %>%
        dplyr::count(outcome) %>% 
        dplyr::arrange(desc(n)) %>% 
        dplyr::mutate(outcome = forcats::fct_reorder(outcome, n))
    
    ggplot(outcomes, aes(outcome, n)) +
        geom_col() +
        coord_flip() +
        labs(x = "", y = "")
})    
```

##

### Table

```{r}
DT::renderDT(
    results(),
    rownames = FALSE,
    colnames = c("Success/Failure", "Advantage/Threat", "Triumph", "Despair", "Outcome"),
    options = list(columnDefs = list(list(className = 'dt-center', targets = 0:4))),
    selection = "none"
)
```
